event_inherited();

if (Flag_Get(FLAG_TYPE.STATIC,FLAG_STATIC.SCENE_004,false)==false){
	if (_phase == 0) {
		if (char_player.x > 160) {
			Cutscene_Begin();
			_phase = 1;
		}
		else Cutscene_End(-1);
	}
	else if (_phase == 1) {
		if (global.event == 1) {
			char_hippo.sprite_index = spr_char_hippo_water_talk_laugh;
			char_hippo.res_idle_sprite[DIR.DOWN] = spr_char_hippo_water_talk_laugh;
			char_hippo.res_talk_sprite[DIR.DOWN] = spr_char_hippo_water_talk_laugh;
			char_hippo.dir = DIR.DOWN;
			global.event = -9999;
		}
		else if (global.event == 2) {
			char_hippo.sprite_index = spr_char_hippo_water_idle;
			char_hippo.res_idle_sprite[DIR.DOWN] = spr_char_hippo_water_idle;
			char_hippo.res_talk_sprite[DIR.DOWN] = spr_char_hippo_water_talk;
			char_hippo.dir = DIR.DOWN;
			global.event = -9999;
		}
		else if (global.event == 3) {
			char_hippo.sprite_index = spr_char_hippo_water_talk_shocked;
			char_hippo.res_idle_sprite[DIR.DOWN] = spr_char_hippo_water_talk_shocked;
			char_hippo.res_talk_sprite[DIR.DOWN] = spr_char_hippo_water_talk_shocked;
			char_hippo.dir = DIR.DOWN;
			global.event = -9999;
		}
		else if (global.event == 4) {
			char_hippo.sprite_index = spr_char_hippo_water_disappear;
			char_hippo.res_idle_sprite[DIR.DOWN] = spr_char_hippo_water_disappear;
			char_hippo.res_talk_sprite[DIR.DOWN] = spr_char_hippo_water_disappear;
			char_hippo.dir = DIR.DOWN;
			global.event = -9999;
		}
				
		C_Execute(0, BGM_SetVolume, [0, 0, 30]);
		C_MoveChar(0, char_player, 280, 310, false, 30);
		C_Wait(0, 30);
		C_Execute(1, variable_instance_set, [char_player, "dir", DIR.UP]);
		C_Wait(1, 30);
		C_Execute(2, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.0"), ""]);
		C_Execute(2, Dialog_Start, [false]);
		C_WaitUntilDestroy(2, ui_dialog);
		C_Wait(3, 60);
		C_FadeFader(4, 1, 0, 7, 0, c_white);
		C_PlaySfx(4, bgm_hippo_appear, 0.95);
		C_PlaySfx(4, snd_damage, 0.95);
		C_Execute(4, variable_instance_set, [camera, "target", char_hippo]);
		C_Execute(4, variable_instance_set, [camera, "scale_x", 3]);
		C_Execute(4, variable_instance_set, [camera, "scale_y", 3]);
		C_Execute(4, variable_instance_set, [camera, "angle", 6]);
		C_Execute(4, Camera_Shake, [10, 10, 0, 0, true, true]);
		C_Execute(4, instance_create_depth, [camera.x, camera.y, 0, ui_action_lines]);
		C_Execute(4, variable_instance_set, [char_hippo, "visible", true]);
		C_Execute(4, variable_instance_set, [char_hippo, "sprite_index", spr_char_hippo_water]);
		C_Execute(4, variable_instance_set, [char_hippo, "image_speed", 1]);
		C_Wait(4, 33);
		C_CreateAnim(5, camera, "target", 0, 0, real(camera.target), -4, 1, false, 15);
		C_CreateAnim(5, camera, "target", 0, 0, -4, real(char_player), 1, false, 30);
		C_CreateAnim(5, camera, "scale_x", ANIM_TWEEN.CIRC, ANIM_EASE.OUT, camera.scale_x, 2, 15, false);
		C_CreateAnim(5, camera, "scale_y", ANIM_TWEEN.CIRC, ANIM_EASE.OUT, camera.scale_y, 2, 15, false);
		C_CreateAnim(5, camera, "angle", ANIM_TWEEN.CIRC, ANIM_EASE.OUT, camera.angle, 0, 15, false);
		C_CreateAnim(5, ui_action_lines, "image_alpha", 0, 0, 1, 0, 15, false, 15);
		C_CreateAnim(5, camera, "x", 0, 0, char_hippo.x - (camera.width / 4), char_player.x - (camera.width / 4), 15, false, 15);
		C_CreateAnim(5, camera, "y", 0, 0, char_hippo.y - (camera.width / 4), char_player.y - (camera.width / 4), 15, false, 15);
		C_Execute(5, variable_instance_set, [char_hippo, "sprite_index", spr_char_hippo_water_appear]);
		C_Execute(5, variable_instance_set, [char_hippo, "direction", point_direction(char_hippo.x, char_hippo.y, char_player.x, char_player.y)]);
		C_Execute(5, variable_global_set, ["event",-9999]);
		C_Execute(5, array_set, [char_hippo.res_idle_sprite, DIR.DOWN, spr_char_hippo_water_idle_angry]);
		C_Execute(5, array_set, [char_hippo.res_talk_sprite, DIR.DOWN, spr_char_hippo_water_talk_angry]);
		C_Wait(5, 45);
		C_Execute(6, instance_destroy, [ui_action_lines]);
		C_Execute(6, variable_instance_set, [camera, "target", noone]);
		C_Execute(6, BGM_Stop, [0]);
		C_Execute(6, BGM_Play, [0, bgm_hippo]);
		C_Execute(6, BGM_SetPitch, [0, 0.95]);
		C_Execute(6, variable_instance_set, [char_hippo, "image_speed", 1]);
		C_Execute(6, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.1"), "{char_link 4}{voice 5}"]);
		C_Execute(6, Dialog_Start, [false]);
		C_WaitUntilDestroy(6, ui_dialog);
		C_Execute(7, variable_instance_set, [char_hippo, "speed", 0.25]);
		C_Execute(7, variable_instance_set, [char_player, "vspeed", 0.1]);
		C_Execute(7, variable_instance_set, [char_player, "image_speed", 0.25]);
		C_Wait(7, 30);
		C_Execute(8, variable_instance_set, [char_hippo, "speed", 0]);
		C_Execute(8, variable_instance_set, [char_player, "vspeed", 0]);
		C_Execute(8, variable_instance_set, [char_player, "image_index", 0]);
		C_Execute(8, variable_instance_set, [char_player, "image_speed", 0]);
		C_Execute(8, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.2"), "{char_link 4}{voice 5}"]);
		C_Execute(8, Dialog_Start, [false]);
		C_WaitUntilDestroy(8, ui_dialog);
		C_Execute(9, variable_instance_set, [char_hippo, "speed", 0.25]);
		C_Execute(9, variable_instance_set, [char_player, "vspeed", 0.1]);
		C_Execute(9, variable_instance_set, [char_player, "image_speed", 0.25]);
		C_Wait(9, 30);
		C_Wait(10, 30);
		C_Execute(11, BGM_Stop, [0]);
		C_Execute(11,Anim_Destroy,[camera]);
		C_Execute(11, variable_instance_set, [char_hippo, "speed", 0]);
		C_Execute(11, variable_instance_set, [char_player, "vspeed", 0]);
		C_Execute(11, variable_instance_set, [char_player, "image_index", 0]);
		C_Execute(11, variable_instance_set, [char_player, "image_speed", 0]);
		C_Execute(11, method_call, [camera.moveToObject, [char_hippo, 15]]);
		C_CreateAnim(11, camera, "target", 0, 0, real(camera.target), real(char_hippo), 1, false, 15);
		C_CreateAnim(11, camera, "scale_x", 0, 0, camera.scale_x, 2.5, 30, false, 15);
		C_CreateAnim(11, camera, "scale_y", 0, 0, camera.scale_y, 2.5, 30, false, 15);
		C_Execute(11, array_set, [char_hippo.res_idle_sprite, DIR.DOWN, spr_char_hippo_water_idle_blink]);
		C_Execute(11, array_set, [char_hippo.res_talk_sprite, DIR.DOWN, spr_char_hippo_water_talk_blink]);
		C_Execute(11, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.3"), "{char_link 4}{effect 0}{voice 5}"]);
		C_Execute(11, Dialog_Start, [false]);
		C_WaitUntilDestroy(11, ui_dialog);
		C_Execute(12,Anim_Destroy,[camera]);
		C_CreateAnim(12, camera, "target", 0, 0, real(camera.target), -4, 1, false, 5);
		C_CreateAnim(12, camera, "scale_x", 0, 0, camera.scale_x, 2, 5, false);
		C_CreateAnim(12, camera, "scale_y", 0, 0, camera.scale_y, 2, 5, false);
		C_Execute(12, array_set, [char_hippo.res_idle_sprite, DIR.DOWN, spr_char_hippo_water_idle_shocked]);
		C_Execute(12, array_set, [char_hippo.res_talk_sprite, DIR.DOWN, spr_char_hippo_water_talk_shocked]);
		C_Execute(12, instance_create_depth, [char_hippo.x, char_hippo.y - char_hippo.sprite_height - 5, 0, exclamation]);
		C_Execute(12, instance_create_depth, [char_player.x, char_player.y - char_player.sprite_height - 5, 0, exclamation]);
		C_Execute(12, variable_instance_set, [char_hippo, "sprite_index", spr_char_hippo_water_idle_shocked]);
		C_Execute(12, variable_instance_set, [char_player, "dir", DIR.LEFT]);
		C_Execute(12, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.4"), "{voice 4}{face 2}{face_emotion 6}"]);
		C_Execute(12, Dialog_Start, [true]);
		C_WaitUntilDestroy(12, ui_dialog);
		C_Execute(13, instance_create_depth, [110, 240, -2000, char_serval]);
		C_MoveChar(13, char_serval, 150, 310, false, 30);
		C_Wait(13, 30);
		C_Execute(14, variable_global_set, ["event",-9999]);
		C_Execute(14, variable_instance_set, [char_hippo, "sprite_index", spr_char_hippo_water_idle]);
		C_Execute(14, array_set, [char_hippo.res_idle_sprite, DIR.DOWN, spr_char_hippo_water_idle]);
		C_Execute(14, array_set, [char_hippo.res_talk_sprite, DIR.DOWN, spr_char_hippo_water_talk]);
		C_Execute(14, array_set, [char_hippo.res_move_sprite, DIR.RIGHT, spr_char_hippo_water_idle]);
		C_MoveChar(14, char_serval, char_player.x - 30, char_player.y, false, 30);
		C_Wait(14, 30);
		C_Execute(15, variable_instance_set, [char_serval, "dir", DIR.UP]);
		C_Execute(15, variable_instance_set, [char_player, "dir", DIR.UP]);
		C_Wait(15, 30);
		C_Execute(16, BGM_Play, [0, bgm_savannah]);
		C_Execute(16, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.5"), "{char_link 2}{voice 4}{face 2}{face_emotion 6}"]);
		C_Execute(16, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.6"), "{char_link 4}{voice 5}"]);
		C_Execute(16, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.7"), "{char_link 2}{voice 4}{face 2}{face_emotion 6}"]);
		C_Execute(16, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.8"), "{char_link 4}{voice 5}"]);
		C_Execute(16, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.9"), "{char_link 2}{voice 4}{face 2}{face_emotion 9}"]);
		C_Execute(16, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.10"), "{char_link 4}{voice 5}"]);
		C_Execute(16, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.11"), "{char_link 2}{voice 4}{face 2}{face_emotion 5}"]);
		C_Execute(16, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.12"), "{char_link 4}{event 3}{voice 5}"]);
		C_Execute(16, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.13"), "{char_link 4}{event 2}{voice 5}"]);
		C_Execute(16, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.14"), "{char_link 4}{event 1}{voice 5}"]);
		C_Execute(16, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.15"), "{char_link 2}{voice 4}{face 2}{face_emotion 4}{event 2}"]);
		C_Execute(16, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.16"), "{char_link 4}{event 1}{voice 5}"]);
		C_Execute(16, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.17"), "{char_link 2}{voice 4}{face 2}{face_emotion 6}{event 2}"]);
		C_Execute(16, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.18"), "{char_link 2}{voice 4}{face 2}{face_emotion 2}"]);
		C_Execute(16, Dialog_Start, [true]);
		C_WaitUntilDestroy(16, ui_dialog);
		C_MoveChar(17, char_player, 20, 0, true, 25);
		C_MoveChar(17, char_serval, 20, 0, true, 25);
		C_Wait(17, 20);
		C_CreateAnim(18, char_hippo, "x", 0, 0, char_hippo.x, char_player.x, 5, false);
		C_Wait(18, 5);
		C_Execute(19, variable_instance_set, [char_serval, "dir", DIR.UP]);
		C_Execute(19, variable_instance_set, [char_player, "dir", DIR.UP]);
		C_Execute(19, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.19"), "{char_link 4}{voice 5}"]);
		C_Execute(19, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.20"), "{char_link 2}{voice 4}{face 2}{face_emotion 3}"]);
		C_Execute(19, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.21"), "{char_link 4}{voice 5}"]);
		C_Execute(19, Dialog_Add, [Lang_GetString("cutscene.savannah.lake.22"), "{char_link 2}{voice 4}{face 2}{face_emotion 7}"]);
		C_Execute(19, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.23"), "{char_link 2}{voice 4}{face 2}{face_emotion 6}"]);
		C_Execute(19, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.24"), "{char_link 4}{voice 5}"]);
		C_Execute(19, Dialog_Start, [true]);
		C_WaitUntilDestroy(19, ui_dialog);
		C_CreateAnim(20, char_hippo, "x", 0, 0, char_hippo.x, char_player.x, 5, false);
		C_Wait(20, 30);
		C_Execute(21, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.25"), "{char_link 4}{voice 5}"]);
		C_Execute(21, Dialog_Start, [true]);
		C_WaitUntilDestroy(21, ui_dialog);
		C_Wait(22, 60);
		C_Execute(23, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.26"), "{char_link 4}{voice 5}"]);
		C_Execute(23, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.27"), "{char_link 4}{voice 5}"]);
		C_Execute(23, Dialog_Start, [true]);
		C_WaitUntilDestroy(23, ui_dialog);
		C_Execute(24, variable_instance_set, [char_player, "sprite_index", spr_char_kaban_down_lookright]);
		C_Wait(24, 60);
		C_Execute(25, variable_instance_set, [char_player, "dir", DIR.UP]);
		C_Execute(25, variable_instance_set, [char_player, "sprite_index", spr_char_kaban_up]);
		C_Execute(25, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.28"), "{char_link 4}{voice 5}"]);
		C_Execute(25, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.29"), "{char_link 4}{voice 5}"]);
		C_Execute(25, Dialog_Start, [true]);
		C_WaitUntilDestroy(25, ui_dialog);
		C_Wait(26, 30);
		C_Execute(27, variable_instance_set, [char_player, "dir", DIR.DOWN]);
		C_CreateAnim(27, char_player, "y", 0, 0, char_player.y, 10, 15, true);
		C_CreateAnim(27, char_player, "image_index", 0, 0, 0, 4, 15, false);
		C_Wait(27, 60);
		if (instance_exists(char_serval)) C_CreateAnim(28, char_hippo, "x", 0, 0, char_hippo.x, char_serval.x + 10, 10, false);
		C_Execute(28, variable_instance_set, [char_serval, "dir", DIR.UP]);
		C_Execute(28, variable_instance_set, [char_player, "dir", DIR.UP]);
		C_Execute(28, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.30"), "{char_link 4}{voice 5}"]);
		C_Execute(28, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.31"), "{char_link 4}{voice 5}"]);
		C_Execute(28, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.32"), "{char_link 4}{voice 5}"]);
		C_Execute(28, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.33"), "{char_link 2}{voice 4}{face 2}{face_emotion 4}"]);
		C_Execute(28, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.34"), "{char_link 4}{voice 5}"]);
		C_Execute(28, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.35"), "{char_link 2}{voice 4}{face 2}{face_emotion 6}{scale 1.2}"]);
		C_Execute(28, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.36"), "{char_link 4}{voice 5}"]);
		C_Execute(28, Dialog_Start, [true]);
		C_WaitUntilDestroy(28, ui_dialog);
		C_Execute(29, BGM_SetVolume, [0, 0, 60]);
		C_FadeFader(29, 0, 1, 60, 0, c_black);
		C_Wait(29, 120);
		C_Execute(30, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.37"), ""]);
		C_Execute(30, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.38"), ""]);
		C_Execute(30, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.39"), ""]);
		C_Execute(30, Dialog_Start, [false]);
		C_WaitUntilDestroy(30, ui_dialog);
		C_FadeFader(31, 1, 0, 60);
		C_Execute(31, BGM_SetVolume, [0, 1, 60]);
		C_Wait(31, 120);
		C_Execute(32, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.40"), "{char_link 2}{voice 4}{face 2}{face_emotion 3}"]);
		C_Execute(32, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.41"), "{char_link 4}{voice 5}"]);
		C_Execute(32, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.42"), "{char_link 4}{voice 5}"]);
		C_Execute(32, Dialog_Add_Ext, [Lang_GetString("cutscene.savannah.lake.43"), "{char_link 2}{voice 4}{face 2}{face_emotion 0}"]);
		C_Execute(32, Dialog_Start, [true]);
		C_WaitUntilDestroy(32, ui_dialog);
		C_MoveChar(33, char_serval, 420, 310, false, 80);
		C_MoveChar(33, camera, char_player.x - (camera.width / camera.scale_x / 2), 180 - 10, false, 60);
		C_Execute(33, Flag_Set, [FLAG_TYPE.STATIC, FLAG_STATIC.CAN_RUN, true]);
		C_Wait(33, 80);
		C_MoveChar(34, char_serval, 420, 460, false, 60);
		C_Wait(34, 60);
		C_Execute(35, variable_global_set, ["event", 4]);
		C_Execute(35, variable_instance_set, [char_hippo, "image_speed", 1]);
		C_Wait(35, 60);
		C_Execute(36, variable_instance_set, [char_hippo, "visible", false]);
		C_Execute(36, variable_instance_set, [camera, "target", char_player]);
		C_Execute(36, variable_instance_set, [char_save, "visible", true]);
		C_Execute(36, Create_Overlay_Text, [Lang_GetString("cutscene.savannah.lake.44"),0]);
		C_Execute(36, instance_destroy, [char_serval]);
		C_Execute(36, variable_global_set, ["event", -9999]);
		C_Execute(36, Flag_Set, [FLAG_TYPE.STATIC, FLAG_STATIC.SCENE_004, true]);
		Cutscene_End(36);
	}
}
else {
	if (_teleported_char == true) { 
		instance_destroy(char_hippo);
	}
	instance_destroy(char_forcefield);
	char_save.visible=true;
}