event_inherited();

if (Flag_Get(FLAG_TYPE.STATIC, FLAG_STATIC.SCENE_001, false) == false) {
	if (cutscene._current_order < 1)
		char_player.sprite_index = spr_char_kaban_sleep;
			
	C_Execute(0, BGM_Play, [0, bgm_birdnoise]);
	C_Wait(0, 60);
	C_Execute(1, variable_instance_set, [camera, "target", noone]);
	C_Execute(1, variable_instance_set, [char_player, "sprite_index", spr_char_kaban_down_hat_rearrange]);
	C_Execute(1, variable_instance_set, [char_player, "image_speed", 1.5]);
	C_Wait(1, 60);
	C_Execute(2, variable_instance_set, [char_player, "_draw_hat", true]);
	C_Execute(2, variable_instance_set, [char_player, "image_speed", 0]);
	C_Execute(2, variable_instance_set, [char_player, "image_index", 0]);
	C_Execute(2, variable_instance_set, [char_player, "dir", DIR.LEFT]);
	C_Wait(2, 10);
	C_Execute(3, variable_instance_set, [char_player, "dir", DIR.UP]);
	C_Wait(3, 10);
	C_Execute(4, variable_instance_set, [char_player, "dir", DIR.DOWN]);
	C_Wait(4, 30);
	C_Execute(5, instance_create_depth, [char_player.x, char_player.y - char_player.sprite_width - 15, 0, exclamation]);
	C_Execute(5, variable_instance_set, [char_player, "dir", DIR.RIGHT]);
	C_Execute(5, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.0"), "{char_link 2}{voice 4}{face 2}{face_emotion 2}"]);
	C_Execute(5, Dialog_Start, [true]);
	C_WaitUntilDestroy(5, ui_dialog);
	C_Execute(6, variable_instance_set, [char_player, "dir", DIR.DOWN]);
	C_MoveChar(6, char_serval, 200, 265, false, 60);
	C_Execute(6, BGM_SetVolume, [0, 0, 30]);
	C_Wait(6, 60);
	C_Execute(7, BGM_Stop, [0]);
	C_Execute(7, BGM_Play, [0, bgm_serval]);
	C_Execute(7, variable_instance_set, [char_serval, "dir", DIR.UP]);
	C_Execute(7, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.1"), "{char_link 2}{voice 4}{face 2}{face_emotion 1}"]);
	C_Execute(7, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.2"), "{char_link 2}{voice 4}{face 2}{face_emotion 3}"]);
	C_Execute(7, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.3"), "{char_link 2}{voice 4}{face 2}{face_emotion 2}"]);
	C_Execute(7, Dialog_Start, [true]);
	C_WaitUntilDestroy(7, ui_dialog);
	C_Wait(8, 30);
	C_Execute(9, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.4"), "{char_link 2}{voice 4}{face 2}{face_emotion 2}"]);
	C_Execute(9, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.5"), "{char_link 2}{voice 4}{face 2}{face_emotion 0}"]);
	C_Execute(9, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.6"), "{char_link 2}{voice 4}{face 2}{face_emotion 4}"]);
	C_Execute(9, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.7"), "{char_link 2}{voice 4}{face 2}{face_emotion 2}"]);
	C_Execute(9, Dialog_Start, [true]);
	C_WaitUntilDestroy(9, ui_dialog);
	C_Execute(10, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.8"), "{char_link 2}{voice 4}{face 2}{face_emotion 0}"]);
	C_Execute(10, Dialog_Start, [true]);
	C_WaitUntilDestroy(10, ui_dialog);
	C_Execute(11, variable_instance_set, [char_serval, "dir", DIR.UP]);
	/*C_Wait(4, 30);
	C_MoveChar(5, char_player, 0, -20, true, 30);
	C_Wait(5, 30);
	C_PlaySfx(6, snd_exclamation);
	C_CreateAnim(6, char_serval, "y", ANIM_TWEEN.SINE, ANIM_EASE.OUT, char_serval.y, -5, 3, true);
	C_CreateAnim(6, char_serval, "y", ANIM_TWEEN.SINE, ANIM_EASE.IN, char_serval.y, 5, 3, true, 3);
	C_Wait(6, 6);
	C_CreateAnim(7, char_serval, "y", 0, 0, char_serval.y, char_player.y, 5, false);
	C_CreateAnim(7, char_serval, "y", 0, 0, char_serval.y, 250, 5, false, 5);
	C_CreateAnim(7, char_player, "y", 0, 0, char_player.y, 250, 5, false, 5);
	C_Wait(7, 10);
	C_PlaySfx(8, snd_noise);
	C_Execute(8, variable_instance_set, [char_player, "dir", DIR.RIGHT]);
	C_Execute(8, variable_instance_set, [char_serval, "dir", DIR.LEFT]);
	C_CreateAnim(8, char_serval, "x", 0, 0, char_serval.x, 40, 30, true);
	C_CreateAnim(8, char_serval, "image_index", 0, 0, 0, 8, 30, false);
	*/
	C_Wait(11, 60);
	C_Execute(12, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.9"), "{voice 4}{face 2}{face_emotion 4}"]);
	C_Execute(12, Dialog_Start, [true]);
	C_WaitUntilDestroy(12, ui_dialog);
	C_Execute(13, variable_instance_set, [char_serval, "dir", DIR.DOWN]);
	C_Wait(13, 30);
	C_Execute(14, Cutscene_ChangeOrder, [15]);
	C_Execute(15, variable_instance_set, [char_serval, "dir", DIR.UP]);
	C_PlaySfx(15, snd_exclamation);
	C_CreateAnim(15, char_serval, "y", ANIM_TWEEN.SINE, ANIM_EASE.OUT, char_serval.y, -5, 3, true);
	C_CreateAnim(15, char_serval, "y", ANIM_TWEEN.SINE, ANIM_EASE.IN, char_serval.y, 5, 3, true, 3);
	C_Wait(15, 15);
	C_CreateAnim(16, char_serval, "y", 0, 0, char_serval.y, char_player.y, 5, false);
	C_CreateAnim(16, char_serval, "y", 0, 0, char_serval.y-(char_serval.y-char_player.y), 250, 5, false, 5);
	C_CreateAnim(16, char_player, "y", 0, 0, char_player.y, 250, 5, false, 5);
	C_Wait(16, 10);
	C_PlaySfx(17, snd_noise);
	C_Execute(17, variable_instance_set, [char_player, "dir", DIR.RIGHT]);
	C_Execute(17, variable_instance_set, [char_serval, "dir", DIR.LEFT]);
	C_CreateAnim(17, char_serval, "x", 0, 0, char_serval.x, 40, 30, true);
	C_CreateAnim(17, char_serval, "image_index", 0, 0, 0, 8, 30, false);
	C_Wait(17, 30);
	C_Execute(18, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.10"), "{char_link 2}{voice 4}{face 2}{face_emotion 0}"]);
	C_Execute(18, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.11"), "{char_link 2}{voice 4}{face 2}{face_emotion 0}"]);
	C_Execute(18, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.12"), "{char_link 2}{voice 4}{face 2}{face_emotion 4}"]);
	C_Execute(18, Dialog_Start, [true]);
	C_WaitUntilDestroy(18, ui_dialog);
	C_Execute(19, variable_instance_set, [char_serval, "dir", DIR.UP]);
	C_Wait(19, 30);
	C_Execute(20, variable_instance_set, [char_serval, "dir", DIR.LEFT]);
	C_Execute(20, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.13"), "{char_link 2}{voice 4}{face 2}{face_emotion 0}"]);
	C_Execute(20, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.14"), "{char_link 2}{voice 4}{face 2}{face_emotion 8}"]);
	C_Execute(20, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.15"), "{char_link 2}{voice 4}{face 2}{face_emotion 4}"]);
	C_Execute(20, Dialog_Add_Ext, [Lang_GetString("cutscene.serval.greet.16"), "{char_link 2}{voice 4}{face 2}{face_emotion 2}"]);
	C_Execute(20, Dialog_Start, [true]);
	C_WaitUntilDestroy(20, ui_dialog);
	C_MoveChar(21, char_serval, 420, 260, false, 60);
	C_Execute(21, BGM_SetVolume, [0, 0, room_speed]);
	C_Wait(21, 60);
	C_MoveChar(22, camera, char_player.x - (camera.width / camera.scale_x / 2), char_player.y - (camera.width / camera.scale_y / 2), false, 30);
	C_Wait(22, 30);
	C_Execute(23, variable_instance_set, [camera, "target", char_player]);
	C_Execute(23, Create_Trophy, [spr_trophy_tree]);
	C_Execute(23, Flag_Set, [FLAG_TYPE.STATIC, FLAG_STATIC.SCENE_001, true]);
	Cutscene_End(23);
}
else {
	instance_destroy(char_serval);
}