event_inherited();

if(Flag_Get(FLAG_TYPE.STATIC,FLAG_STATIC.SCENE_013,false)==false){
	char_chameleon.dark=true;
	char_chameleon.res_pose_sprite=spr_char_chameleon_down_dark;
	if(cutscene._current_order<14)
		char_porcupine.sprite_index=spr_char_porcupine_hide;
	C_MoveChar(0,char_player,120,char_player.y,false,30);
	C_Wait(0,60);
	C_Execute(1,variable_instance_set,[char_player,"dir",DIR.LEFT]);
	C_Wait(1,15);
	C_Execute(2,variable_instance_set,[char_player,"dir",DIR.RIGHT]);
	C_Wait(2,15);
	C_MoveChar(3,char_player,170,310,false,60,false,DIR.UP);
	C_Wait(3,60);
	C_Execute(4,BGM_SetVolume,[0,0,60]);
	C_MoveChar(4,char_player,170,210,false,60,false,DIR.UP);
	C_Wait(4,60);
	C_Execute(5,variable_instance_set,[char_player,"dir",DIR.RIGHT]);
	C_MoveChar(5,char_chameleon,char_player.x+40,char_chameleon.y,false,60,true,DIR.LEFT,snd_step_water);
	C_Wait(5,120);
	C_Execute(6,variable_instance_set,[char_chameleon,"dir",DIR.DOWN]);
	C_Wait(6,15);
	C_Execute(7,variable_instance_set,[char_chameleon,"dir",DIR.UP]);
	C_Wait(7,15);
	C_Execute(8,variable_instance_set,[char_chameleon,"dir",DIR.LEFT]);
	C_Wait(8,60);
	C_PlaySfx(9,snd_exclamation);
	C_Execute(9,instance_create_depth,[char_chameleon.x,char_chameleon.y-char_chameleon.sprite_height-5,-9999,exclamation]);
	C_Wait(9,30);
	C_MoveChar(10,char_chameleon,char_player.x+20,char_chameleon.y,false,5,true,DIR.LEFT,snd_step_water);
	C_Wait(10,15);
	C_PlaySfx(11,snd_grab);
	C_Execute(11,variable_instance_set,[char_chameleon,"sprite_index",spr_char_chameleon_left_catch]);
	C_Execute(11,variable_instance_set,[char_chameleon,"image_index",0]);
	C_Execute(11,variable_instance_set,[char_chameleon,"image_speed",0]);
	C_CreateAnim(11,char_chameleon,"image_index",0,0,0,sprite_get_number(spr_char_chameleon_left_catch),160,false,0,ANIM_MODE.ONESHOT);
	C_Wait(11,220);
	C_Execute(12,variable_instance_set,[char_chameleon,"sprite_index",spr_char_chameleon_left_dark]);
	C_Execute(12,variable_instance_set,[char_chameleon,"dir",DIR.LEFT]);
	C_MoveChar(12,char_chameleon,60,char_chameleon.y,false,30,true,DIR.LEFT,snd_step_water);
	C_Wait(12,30);
	C_MoveChar(13,char_chameleon,80,char_chameleon.y,false,30,true,DIR.LEFT,snd_step_water);
	C_Wait(13,60);
	C_MoveChar(14,char_chameleon,-40,char_chameleon.y,false,60,true,DIR.LEFT,snd_step_water);
	C_Wait(14,60);
	C_Execute(15,BGM_Play,[0,bgm_rain]);
	C_Execute(15,BGM_SetVolume,[0,0]);
	C_Execute(15,BGM_SetVolume,[0,1,30]);
	C_Execute(15,Dialog_Add_Ext,[Lang_GetString("cutscene.plains.porcupine_talk.0"),"{voice 12}"]);
	C_Execute(15,Dialog_Start,[false]);
	C_Execute(15,array_set,[char_porcupine.res_idle_sprite,DIR.RIGHT,spr_char_porcupine_hide]);
	C_Execute(15,array_set,[char_porcupine.res_move_sprite,DIR.RIGHT,spr_char_porcupine_hide]);
	C_MoveChar(15,char_porcupine,char_player.x-40,char_porcupine.y,false,60);
	C_WaitUntilDestroy(15,ui_dialog);
	C_Wait(16,60);
	C_Execute(17,Dialog_Add_Ext,[Lang_GetString("cutscene.plains.porcupine_talk.1"),"{voice 12}"]);
	C_Execute(17,Dialog_Start,[false]);
	C_WaitUntilDestroy(17,ui_dialog);
	C_Execute(18,variable_instance_set,[char_porcupine,"res_pose_sprite",spr_char_porcupine_down]);
	C_Execute(18,array_set,[char_porcupine.res_idle_sprite,DIR.RIGHT,spr_char_porcupine_right]);
	C_Execute(18,array_set,[char_porcupine.res_move_sprite,DIR.RIGHT,spr_char_porcupine_right]);
	C_Execute(18,variable_instance_set,[char_porcupine,"dir",DIR.DOWN]);
	C_Wait(18,30);
	C_Execute(19,variable_instance_set,[char_porcupine,"dir",DIR.RIGHT]);
	C_Execute(19,Dialog_Add_Ext,[Lang_GetString("cutscene.plains.porcupine_talk.2"),"{voice 12}"]);
	C_Execute(19,Dialog_Add_Ext,[Lang_GetString("cutscene.plains.porcupine_talk.3"),"{voice 12}"]);
	C_Execute(19,Dialog_Start,[false]);
	C_WaitUntilDestroy(19,ui_dialog);
	C_MoveChar(20,char_porcupine,40,char_porcupine.y,false,30);
	C_MoveChar(20,char_player,80,char_player.y,false,30);
	C_Wait(20,30);
	C_Execute(21,variable_instance_set,[char_porcupine,"dir",DIR.RIGHT]);
	C_Wait(21,30);
	C_Execute(22,Dialog_Add_Ext,[Lang_GetString("cutscene.plains.porcupine_talk.4"),"{voice 12}{face 5}{face_emotion 0}"]);
	C_Execute(22,Dialog_Add_Ext,[Lang_GetString("cutscene.plains.porcupine_talk.5"),"{voice 12}{face 5}{face_emotion 0}"]);
	C_Execute(22,Dialog_Add_Ext,[Lang_GetString("cutscene.plains.porcupine_talk.6"),"{voice 12}{face 5}{face_emotion 0}"]);
	C_Execute(22,Dialog_Start,[false]);
	C_WaitUntilDestroy(22,ui_dialog);
	C_MoveChar(23,char_player,90,char_player.y,false,30,false,DIR.LEFT);
	C_Wait(23,30);
	C_Execute(24,Dialog_Add_Ext,[Lang_GetString("cutscene.plains.porcupine_talk.7"),"{voice 12}{face 5}{face_emotion 1}"]);
	C_Execute(24,Dialog_Add_Ext,[Lang_GetString("cutscene.plains.porcupine_talk.8"),"{voice 12}{face 5}{face_emotion 2}"]);
	C_Execute(24,Dialog_Add_Ext,[Lang_GetString("cutscene.plains.porcupine_talk.9"),"{voice 12}{face 5}{face_emotion 2}"]);
	C_Execute(24,Dialog_Add_Ext,[Lang_GetString("cutscene.plains.porcupine_talk.10"),"{voice 12}{face 5}{face_emotion 1}"]);
	C_Execute(24,Dialog_Add_Ext,[Lang_GetString("cutscene.plains.porcupine_talk.11"),"{voice 12}{face 5}{face_emotion 3}"]);
	C_Execute(24,Dialog_Add_Ext,[Lang_GetString("cutscene.plains.porcupine_talk.12"),"{voice 12}{face 5}{face_emotion 4}"]);
	C_Execute(24,Dialog_Add_Ext,[Lang_GetString("cutscene.plains.porcupine_talk.13"),"{voice 12}{face 5}{face_emotion 4}"]);
	C_Execute(24,Dialog_Start,[false]);
	C_WaitUntilDestroy(24,ui_dialog);
	C_MoveChar(25,char_player,-20,char_player.y,false,60);
	C_MoveChar(25,char_porcupine,-60,char_player.y,false,60);
	C_Wait(25,60);
	C_FadeFader(26,-1,1,30);
	C_Wait(26,30);
	C_FadeFader(27,-1,0,30);
	C_Execute(27,room_goto,[room_plains_2]);
	Cutscene_End(27);
}